# Generated by Django 4.2.5 on 2024-10-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SIqwFJzb0VvXTT962pBms1$LojnRrJOKmOnWaa0md1ZgC5S51u/Wng2kjT3qEnIYIw=', max_length=128),
        ),
    ]
