# Generated by Django 4.2.5 on 2024-10-06 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$87F6J8CxSZ9heUU5XSGIb5$CtDBhpNVuLMMkQItiTuiPizUA6wwpvU3JSJXLdYRsZE=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$KptlZd5wyZyV6omu3uYvBn$hPzKJQVE7JcZMJUqdndnT/JW97XK9tNaUtbCmCRvYWc=', max_length=128),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('loginTime', models.TimeField(auto_now_add=True)),
                ('logoutTime', models.TimeField(blank=True, null=True)),
                ('consumedTime', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_as_parent', to='students.student')),
            ],
        ),
    ]
