# Generated by Django 4.2.5 on 2024-10-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_staff_password_alter_student_password_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$OLiHFOr8bMKpgeuwWaJmTN$UknWCdCUtYLq4AkRXqRnsW1zAp9/9pnOvNddwO6W6Xk=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=128),
        ),
    ]
