# Generated by Django 4.2.5 on 2024-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_logged_in_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$P2wyLu2YL1dtzCHnBJw5ZS$+0egrqJawAE4AAcP5bT8Z9vK19stpgS2O1NIEtwnwM8=', max_length=128),
        ),
    ]
