# Generated by Django 4.2.5 on 2024-10-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$P80cwIzdkB6yUJbIhjXIA5$wBjjJjQp+oCmqcNS+qivX4TrXrbpDuMP4oFuyufPBII=', max_length=128),
        ),
    ]
