# Generated by Django 4.2.5 on 2024-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_staff_password_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$FK0NMq37TbKNBTRUv9542Y$esiLw37E+5ggfTide2BRP8L8m3vg7PujgbSV3VUTLso=', max_length=128),
        ),
    ]
