# Generated by Django 4.2.5 on 2024-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$on82KCpdb3Q2SzAi62aCR0$9NWyX8x9MB+TVI72l2zhS46vAfSBLcGvffUlbnXpEjo=', max_length=128),
        ),
    ]
