# Generated by Django 4.2.5 on 2024-10-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$YNJEoY1LHmjbAo2EImo8t5$ttfjhhptr7yM+sHglLxZsSuEpbx7EA6ef8OdGMQGCmc=', max_length=128),
        ),
    ]
