# Generated by Django 4.2.5 on 2024-10-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$tXdLE7c1lNykcuj0cXvvAp$ULmLYn5dHgyrzRBFLq1P+IYX2sRi3zXEqNYB/R1v/Gk=', max_length=128),
        ),
    ]
