# Generated by Django 4.2.5 on 2024-10-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$jsWYasQ1uVaN3c8eDHpiBc$PmSWFp5078rg7vUhriHGxQgmSi4WZw3SVvmL/iD4yOQ=', max_length=128),
        ),
    ]
