# Generated by Django 4.2.5 on 2024-10-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qONu7MlxRHIErUCk1GGeBv$B2mPnIr4+gRWoG90dSFTyaFWpcZakJHEnT0IlzKhdNc=', max_length=128),
        ),
    ]
