# Generated by Django 4.2.5 on 2024-10-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$sQEhS9wKizxQWbCialTNS7$W2CI9hGuyVsXbmlW0B3NFs8Gcjz3pwlw7gT2XxyljJ4=', max_length=128),
        ),
    ]
