# Generated by Django 4.2.5 on 2024-10-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_staff_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$SlsNluGSiABpIKO2sSU0ih$nq5SgBvEeWsjG5UxDOYvQocXlhFCuZ46fFbJy4bbtOA=', max_length=128),
        ),
    ]
