# Generated by Django 4.2.13 on 2024-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$PyTyOtxu6Q2m9IzJksn7VB$0lx6UwpEhN1gkX/HU4UrnuDNXheSvndLyhb0uc6yDcE=', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dropped_out', 'Dropped Out')], default='active', max_length=15),
        ),
    ]
