# Generated by Django 4.2.13 on 2024-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_password_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$zpUII5vsaTlfeefwXsWG2f$r8uGvbRhV4JWzyM0NYg7LogcmLaeXWYKXbDb06zcWW8=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Dropped_out', 'Dropped Out')], default='active', max_length=15),
        ),
    ]
