# Generated by Django 4.2.13 on 2024-09-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_password_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xg7z64gbE8j6G1HVoF5JN4$iUzaEuLHnZNAY7tLbYmkLCS35LRI5BQrvlYYqEz/WfU=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Dropped_out', 'Dropped Out')], default='Active', max_length=15),
        ),
    ]
