# Generated by Django 4.2.13 on 2024-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_password_alter_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$HxX5JDlsyVXlFBNPlmkXL7$UBS0AfmYkJqgOUnZZVO8V9ko2RqHCWVQEIB/TAS33Fc=', max_length=128),
        ),
    ]
