# Generated by Django 4.2.13 on 2024-09-17 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Gxln9atXYuQUOLmaPZst7q$kV9oiHCUTs7BLHmv7QNjVKnwtmZqphsRbPJ9R7IbxGA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_studentID', message='Student ID must be in the format XX-XXXX-XXX', regex='^\\d{2}-\\d{4}-\\d{3}$')]),
        ),
    ]
