# Generated by Django 4.2.13 on 2024-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_password_alter_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$xhumaXFhtuoKRPIRwDNEWA$y1+a4vEfhQyFoMG19ZWSRxE72Iu8Gl9o/h85aKDsF4g=', max_length=128),
        ),
    ]
