# Generated by Django 4.2.13 on 2024-09-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$CjqnZjEfhKLM9ZpKBe7PgP$r1UoSc7Lgcw0GeEduUnjFTBCBMEVuJk3vsrdrL02FSc=', max_length=128),
        ),
    ]
