# Generated by Django 4.2.13 on 2024-09-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$ZmeEcXwkPF3qFIlcxLAHLL$R4VXph4RKs1rRPUQ+c377PqSNeDp9Dr8/gBS0QIN2oA=', max_length=128),
        ),
    ]
