# Generated by Django 4.2.13 on 2024-09-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$HLpjnJcBUtkM9h5JvZsUP3$6fVR3YgeqOY38QZ3dJ6ZCgNwpO5BEg+5Mf78meIPxJE=', max_length=128),
        ),
    ]
