# Generated by Django 4.2.13 on 2024-09-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$4oCB1BmhM9j3xlQ93NXNJc$HjQnXZpcJe+5zjjR2iPn9weYI1D1ZmbDZos3EyBIEo4=', max_length=128),
        ),
    ]
