# Generated by Django 4.2.13 on 2024-09-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qxisoFKocgnVSvwVG2YtfE$52vzLWMHzNT0Y1u+Bjo82B2EfSi06e5Xn3MCbw+Dj/k=', max_length=128),
        ),
    ]
