# Generated by Django 4.2.13 on 2024-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$Hw38WZOKmYoLcYvhAYK5hK$T9ppCM8YgZz/mjUsFNCyRmcTH09SMXNv+s7zcb4AAfA=', max_length=128),
        ),
    ]
