# Generated by Django 4.2.13 on 2024-09-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$oa0J7WBXSfORGU3rnW5re7$OGC7q6y1snHLrgsPF38vPViKAXmRxonTOR/BP83iGIU=', max_length=128),
        ),
    ]
