# Generated by Django 4.2.13 on 2024-09-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_student_password_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$go25DZnWdE4wXWYIIXeduK$5Oe+uLyHQYtye/+FyUd47GtThsEKAi0/kQCILX7M2FI=', max_length=128),
        ),
    ]
