# Generated by Django 4.2.13 on 2024-09-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_alter_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$qyqjRKhLgTzDHMLJV5LxQi$WenLT1wmLtB0sa2slOlcIZIQvjGjbJAhRD+wMJ/Cvzk=', max_length=128),
        ),
    ]
