# Generated by Django 4.2.13 on 2024-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_alter_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(default='pbkdf2_sha256$600000$hyP6LosSwsEi8vpoxfEsYq$eIoFTf5Ee0A34MkYvFxWQ6veCe4Nk9lGK+fs60+D5YM=', max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$AtNxexF3sCuhnG6GSkpDEL$Drf+blIIXqMM1HU3+Sz6qUdZtxxS/D77jCsCeF8xnOg=', max_length=128),
        ),
    ]
